const CONFIG={latitude:37.2296,longitude:-80.4139,timezone:'America/New_York',calendarFeedUrl:'https://script.google.com/macros/s/AKfycbyKgHqynYULXBm8FCTn8FdsY0EvL3rjyfYk4kI_hTUWgghhzGIt3vABik8QfrD9uyBklg/exec'};
const CALENDAR_COLORS={Love:'#ef4f78',Anthony:'#2f80ed',Megan:'#39a96b',Hamm:'#8d63d6',Other:'#7d8ea3'};
const CALENDAR_PRIORITY={Love:1,Anthony:2,Megan:3,Hamm:4,Other:99};
let events=[];let sportsEvents=[];
function formatDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function eventColor(e){return e.color||CALENDAR_COLORS[e.calendar]||CALENDAR_COLORS.Other}
function eventPriority(e){return Number.isFinite(e.priority)?e.priority:(CALENDAR_PRIORITY[e.calendar]||99)}
function formatRangeTitle(start,end){const same=start.getFullYear()===end.getFullYear();const a=start.toLocaleDateString('en-US',{month:'long',day:'numeric',year:same?undefined:'numeric'});const b=end.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'});return `${a} – ${b}`}
function updateClock(){const now=new Date();document.getElementById('clock').textContent=now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});document.getElementById('weekday').textContent=now.toLocaleDateString('en-US',{weekday:'long'});document.getElementById('date').textContent=now.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}
function eventSortValue(e){if(e.allDay)return-1;if(e.start)return new Date(e.start).getTime();const m=(e.time||'').match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);if(!m)return Number.MAX_SAFE_INTEGER;let h=Number(m[1])%12;if(m[3].toUpperCase()==='PM')h+=12;return h*60+Number(m[2])}
function compareEvents(a,b){const p=eventPriority(a)-eventPriority(b);if(p)return p;if(a.allDay!==b.allDay)return a.allDay?-1:1;return eventSortValue(a)-eventSortValue(b)}
function renderCalendar(){const now=new Date();now.setHours(12,0,0,0);const start=new Date(now);start.setDate(now.getDate()-now.getDay());const end=new Date(start);end.setDate(start.getDate()+20);document.getElementById('monthTitle').textContent=formatRangeTitle(start,end);const grid=document.getElementById('calendarGrid');grid.innerHTML='';for(let i=0;i<21;i++){const date=new Date(start);date.setDate(start.getDate()+i);const cell=document.createElement('div');cell.className='day';if(date.getMonth()!==now.getMonth())cell.classList.add('outside');if(formatDateKey(date)===formatDateKey(now))cell.classList.add('today');const num=document.createElement('div');num.className='day-number';num.textContent=date.getDate();cell.appendChild(num);const matches=events.filter(e=>formatDateKey(e.date)===formatDateKey(date)).sort(compareEvents);const box=document.createElement('div');box.className='day-events';matches.slice(0,7).forEach(e=>{const row=document.createElement('div');if(e.allDay){row.className='event-row all-day';row.style.borderLeftColor=eventColor(e);row.style.background=`${eventColor(e)}18`;row.textContent=e.title}else{row.className='event-row';row.innerHTML=`<div class="event-wrap"><span class="event-dot" style="background:${eventColor(e)}"></span><span class="event-time">${e.time}</span></div><span class="event-title">${e.title}</span>`}box.appendChild(row)});if(matches.length>7){const more=document.createElement('div');more.className='more-events';more.textContent=`+${matches.length-7} more`;box.appendChild(more)}cell.appendChild(box);grid.appendChild(cell)}}
function minuteOfDay(date){return date.getHours()*60+date.getMinutes()}
function timelineTimeLabel(hour){const d=new Date();d.setHours(hour,0,0,0);return d.toLocaleTimeString('en-US',{hour:'numeric'})}
function renderDayTimeline(container,date,label){const dayEvents=events.filter(e=>formatDateKey(e.date)===formatDateKey(date)).sort((a,b)=>eventSortValue(a)-eventSortValue(b));const allDay=dayEvents.filter(e=>e.allDay);const timed=dayEvents.filter(e=>!e.allDay&&e.start);const col=document.createElement('section');col.className='timeline-day';const header=document.createElement('div');header.className='timeline-day-header';header.innerHTML=`<div class="timeline-day-title">${label}</div><div class="timeline-day-date">${date.toLocaleDateString('en-US',{month:'short',day:'numeric'})}</div>`;col.appendChild(header);const allDayBox=document.createElement('div');allDayBox.className='timeline-all-day';if(allDay.length){allDay.forEach(e=>{const pill=document.createElement('div');pill.className='timeline-all-day-pill';pill.style.borderLeftColor=eventColor(e);pill.style.background=`${eventColor(e)}20`;pill.textContent=e.title;allDayBox.appendChild(pill)})}else{allDayBox.innerHTML='<span class="timeline-all-day-empty">No all-day events</span>'}col.appendChild(allDayBox);const body=document.createElement('div');body.className='timeline-body';for(let hour=6;hour<=24;hour+=2){const y=((hour-6)/(24-6))*100;const line=document.createElement('div');line.className='timeline-hour-line';line.style.top=`${y}%`;line.innerHTML=`<span>${hour===24?'12 AM':timelineTimeLabel(hour)}</span>`;body.appendChild(line)}timed.forEach(e=>{const start=new Date(e.start);const rawStart=minuteOfDay(start);const rawEnd=e.end?minuteOfDay(new Date(e.end)):rawStart+60;const startMin=Math.max(360,Math.min(1439,rawStart));const endMin=Math.max(startMin+20,Math.min(1440,rawEnd));if(rawEnd<=360||rawStart>=1440)return;const top=((startMin-360)/1080)*100;const height=Math.max(4,((endMin-startMin)/1080)*100);const block=document.createElement('div');block.className='timeline-event';block.style.top=`${top}%`;block.style.height=`${height}%`;block.style.borderLeftColor=eventColor(e);block.style.background=`${eventColor(e)}2a`;const endText=e.end?new Date(e.end).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'';block.innerHTML=`<div class="timeline-event-time">${e.time}${endText?'–'+endText:''}</div><div class="timeline-event-title">${e.title}</div>`;body.appendChild(block)});col.appendChild(body);container.appendChild(col)}
function renderAgenda(){const agenda=document.getElementById('agenda');if(!agenda)return;agenda.innerHTML='';agenda.className='agenda timeline-agenda';const today=new Date();today.setHours(12,0,0,0);const tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);renderDayTimeline(agenda,today,'Today');renderDayTimeline(agenda,tomorrow,'Tomorrow')}
function normalizeFeedEvent(item){const date=item.date?new Date(`${item.date}T12:00:00`):new Date(item.start);return{date,start:item.start||null,end:item.end||null,time:item.time||'',title:item.title||'Untitled event',calendar:item.calendar||'Other',sport:item.sport||null,color:item.color||null,priority:Number(item.priority||99),allDay:Boolean(item.allDay),important:Boolean(item.important)}}
function f1SessionName(title){const t=String(title||'');if(/free practice 1|practice 1|\bfp1\b/i.test(t))return'FP1';if(/free practice 2|practice 2|\bfp2\b/i.test(t))return'FP2';if(/free practice 3|practice 3|\bfp3\b/i.test(t))return'FP3';if(/sprint shootout|sprint qualifying/i.test(t))return'Sprint Qual.';if(/\bsprint\b/i.test(t))return'Sprint';if(/qualifying|\bquali\b/i.test(t))return'Qualifying';if(/race/i.test(t))return'Race';return t.replace(/formula\s*1|f1/ig,'').trim()||'Session'}
function f1GrandPrixName(title){let t=String(title||'').replace(/formula\s*1|f1/ig,'').replace(/free practice [123]|practice [123]|\bfp[123]\b|sprint shootout|sprint qualifying|sprint|qualifying|\bquali\b|race/ig,'').replace(/[|:–—-]+/g,' ').replace(/\s+/g,' ').trim();const gp=t.match(/(.+?grand prix)/i);return gp?gp[1].replace(/\b\w/g,c=>c.toUpperCase()):(t||'Grand Prix')}
function sportsLogo(kind){if(kind==='F1')return'<div class="sport-logo f1-logo">F1</div>';if(kind==='PSUF')return'<div class="sport-logo psu-logo">PSU<span>F</span></div>';return'<div class="sport-logo psu-logo">PSU<span>W</span></div>'}
function renderSports(){const box=document.getElementById('sports');if(!box)return;box.innerHTML='';const cutoff=new Date(Date.now()-6*60*60*1000);const upcoming=sportsEvents.filter(e=>!e.start||new Date(e.start)>=cutoff).sort((a,b)=>(a.start?new Date(a.start):a.date)-(b.start?new Date(b.start):b.date));const f1=upcoming.filter(e=>e.sport==='F1'||e.calendar==='F1').slice(0,5);const f1Card=document.createElement('div');f1Card.className='sport-card f1-card';if(f1.length){const gp=f1GrandPrixName(f1[0].title);f1Card.innerHTML=`<div class="sport-head">${sportsLogo('F1')}<div><div class="sport-name">Formula 1</div><div class="sport-subtitle">${gp}</div></div></div><div class="f1-sessions">${f1.map(e=>`<div class="f1-session"><b>${f1SessionName(e.title)}</b><span>${e.date.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</span><strong>${e.time||'TBD'}</strong></div>`).join('')}</div>`}else{f1Card.innerHTML=`<div class="sport-head">${sportsLogo('F1')}<div><div class="sport-name">Formula 1</div><div class="sport-subtitle">Calendar linked • no upcoming weekend</div></div></div>`}box.appendChild(f1Card);[['PSUF','PSU Football'],['PSUW','PSU Wrestling']].forEach(([kind,label])=>{const card=document.createElement('div');card.className='sport-card psu-card';card.innerHTML=`<div class="sport-head">${sportsLogo(kind)}<div><div class="sport-name">${label}</div><div class="sport-subtitle">Schedule feed coming next</div></div></div>`;box.appendChild(card)})}
function getCalendarFeedSettings(){const p=new URLSearchParams(location.search);return{feed:p.get('feed')||CONFIG.calendarFeedUrl,key:window.HOME_DASHBOARD_CALENDAR_KEY||p.get('key')||''}}
function setCalendarStatus(m){const el=document.getElementById('status');if(el)el.textContent=m}
async function loadCalendarFeed(){const{feed,key}=getCalendarFeedSettings();if(!feed)return;if(!key){setCalendarStatus('Calendar waiting for secure Cast configuration…');return}const cb=`homeDashboardCalendar_${Date.now()}`;const script=document.createElement('script');const sep=feed.includes('?')?'&':'?';try{const result=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('feed timed out')),12000);window[cb]=payload=>{clearTimeout(timeout);resolve(payload)};script.onerror=()=>{clearTimeout(timeout);reject(new Error('feed failed to load'))};script.src=`${feed}${sep}callback=${encodeURIComponent(cb)}&key=${encodeURIComponent(key)}&_=${Date.now()}`;document.head.appendChild(script)});if(result&&result.error)throw new Error(result.error);if(!result||!Array.isArray(result.events))throw new Error('invalid feed data');events=result.events.map(normalizeFeedEvent);sportsEvents=Array.isArray(result.sportsEvents)?result.sportsEvents.map(normalizeFeedEvent):[];renderCalendar();renderAgenda();renderSports();setCalendarStatus(`Calendar updated ${new Date().toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})} • ${events.length} events`)}catch(error){setCalendarStatus(`Calendar error: ${error.message}`);console.error(error)}finally{delete window[cb];script.remove()}}
window.setHomeDashboardCalendarKey=function(key){window.HOME_DASHBOARD_CALENDAR_KEY=String(key||'');loadCalendarFeed()};
function weatherInfo(code){if(code===0)return{kind:'sun',text:'Clear'};if([1,2].includes(code))return{kind:'partly',text:'Partly cloudy'};if(code===3)return{kind:'cloud',text:'Cloudy'};if([45,48].includes(code))return{kind:'fog',text:'Foggy'};if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(code))return{kind:'rain',text:'Rain'};if([71,73,75,77,85,86].includes(code))return{kind:'snow',text:'Snow'};if([95,96,99].includes(code))return{kind:'storm',text:'Thunderstorms'};return{kind:'cloud',text:'Weather'}}
function weatherSvg(kind){const sun='<circle cx="24" cy="22" r="8" fill="#f9b233"/><g stroke="#f9b233" stroke-width="2" stroke-linecap="round"><path d="M24 7v5M24 32v5M9 22h5M34 22h5M13.5 11.5l3.5 3.5M31 29l3.5 3.5M34.5 11.5L31 15M17 29l-3.5 3.5"/></g>';const cloud='<path d="M14 31h23a7 7 0 0 0 0-14 11 11 0 0 0-20-3 8 8 0 0 0-3 17Z" fill="#9db2c8"/>';let inner='';if(kind==='sun')inner=sun;else if(kind==='partly')inner=`${sun}<path d="M17 34h21a6 6 0 0 0 0-12 10 10 0 0 0-18-3 7 7 0 0 0-3 15Z" fill="#9db2c8"/>`;else if(kind==='cloud')inner=cloud;else if(kind==='rain')inner=`${cloud}<g stroke="#378bd6" stroke-width="2.3" stroke-linecap="round"><path d="M18 36l-2 6M27 36l-2 6M36 36l-2 6"/></g>`;else if(kind==='snow')inner=`${cloud}<g fill="#4b9cdd"><circle cx="17" cy="39" r="1.7"/><circle cx="27" cy="42" r="1.7"/><circle cx="37" cy="39" r="1.7"/></g>`;else if(kind==='storm')inner=`${cloud}<path d="M27 34h7l-5 6h4l-8 8 2-7h-4z" fill="#f2b233"/>`;else if(kind==='fog')inner=`${cloud}<g stroke="#7d91a6" stroke-width="2" stroke-linecap="round"><path d="M12 36h28M16 41h24"/></g>`;return `<svg viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${inner}</svg>`}
async function loadWeather(){const params=new URLSearchParams({latitude:CONFIG.latitude,longitude:CONFIG.longitude,current:'temperature_2m,weather_code,is_day',daily:'weather_code,temperature_2m_max,temperature_2m_min',temperature_unit:'fahrenheit',timezone:CONFIG.timezone,forecast_days:'5'});try{const response=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`);if(!response.ok)throw new Error(`Weather HTTP ${response.status}`);const data=await response.json();const current=weatherInfo(data.current.weather_code);document.getElementById('weatherIcon').innerHTML=weatherSvg(current.kind);document.getElementById('weatherTemp').textContent=`${Math.round(data.current.temperature_2m)}°`;document.getElementById('weatherText').textContent=current.text;const forecast=document.getElementById('forecast');forecast.innerHTML='';data.daily.time.forEach((dateString,i)=>{const date=new Date(`${dateString}T12:00:00`);const info=weatherInfo(data.daily.weather_code[i]);const item=document.createElement('div');item.className='forecast-day';item.innerHTML=`<div class="forecast-icon">${weatherSvg(info.kind)}</div><div class="forecast-label">${date.toLocaleDateString('en-US',{weekday:'short'})}</div><div class="forecast-temp">${Math.round(data.daily.temperature_2m_max[i])}° / ${Math.round(data.daily.temperature_2m_min[i])}°</div>`;forecast.appendChild(item)})}catch(error){document.getElementById('weatherText').textContent='Weather unavailable';console.error(error)}}
updateClock();renderCalendar();renderAgenda();renderSports();loadCalendarFeed();loadWeather();setInterval(updateClock,1000);setInterval(loadCalendarFeed,60*1000);setInterval(loadWeather,15*60*1000);setInterval(()=>{renderCalendar();renderAgenda();renderSports()},60*1000);
